account/urls.py
from django.urls import  include, re_path
from account.views import mail
from account.views import profile
from account.views import setting
from account.views import *

app_name = 'account'

urlpatterns = [
    re_path('profile/', include([
        re_path(r'^send_email_message$', mail.email_users),
        re_path(r'^inbox$', mail.mail_page),
        re_path(r'^send_private_message$', mail.send_private_message),
        re_path(r'^view_private_message$', mail.view_private_message),
        re_path(r'^delete_private_message$', mail.delete_private_message),
  
        # re_path(r'^update_user$', profile.update_user),
        re_path(r'^settings$', setting.settings_page),
        re_path(r'^update_password$', setting.update_password),
        re_path(r'^update_profile$', profile.update_profile, name='update_profile'),
        
        re_path(r'^view_profile', profile.view_profile, name ='view_profile'),
        re_path(r'^view_my_ads/(?P<user_id>\d+)/$', profile.view_my_ads, name='view_my_ads'),
        re_path(r'^saved_ads/(?P<id>\d+)/$', profile.save_ads, name='saved_ads'),
        re_path(r'^view_message$', profile.view_messages, name= 'view_messages'),
        re_path(r'^view_who_watched$', profile.view_who_watched, name='view_who_watched'),
        re_path(r'^view_settings$', profile.view_settings, name='view_settings'),

        ]))
]

adverts/urls.py
from django.urls import re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'adverts'


urlpatterns = [
    re_path('Ads/', include([
        re_path(r'^post_ad/$', views.post_ad, name='post_ad'),
        re_path(r'^$', views.adverts_list, name='adverts_list'),
        re_path(r'^edit_ad/(?P<id>\d+)/$', views.update_post, name='update_post'), 
        re_path(r'^delete_ad/(?P<id>\d+)/$', views.delete_post, name='delete_post'), 
        re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.advert_detail, name='advert_detail'), 
        re_path(r'^(?P<category_slug>[-\w]+)/$', views.adverts_list_by_category, name='adverts_list_by_category'),
        re_path(r'^likead/(?P<id>\d+)/$', views.like_ad, name='like_ad')


 
   ]))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

landpage/urls.py
from django.urls import include
from django.urls import path, re_path
from . import views
# from django.contrib.sitemaps.views import sitemap
# from .sitemaps import StaticViewSitemap

# sitemaps = {
#     'static': StaticViewSitemap,
# }
app_name = 'landpape'
urlpatterns = [

     #homepages 
     #nologing in required
    re_path(r'^land_page$',views.land_page, name='land_page'),
    re_path(r'^home$', views.land_page, name='home'),
    re_path(r'^welcome/$', views.welcome, name='welcome'),
    re_path(r'^aboutus$', views.about_us, name='about_us'),
    re_path(r'^faqs$', views.faqs, name='faqs'),
    re_path(r'^pricingtable$', views.pricingtable, name='pricingtable'),
    re_path(r'^contactus$', views.contact_us, name='contact_us'), 
  

    
    # re_path(r'^edit/', views.edit, name='edit'),
                  
#     # Off-Convas Stuff
#     re_path(r'^terms$', terms.terms_page, name='terms'),
#     re_path(r'^privacy', privacy.privacy_page, name='privacy'),
#     re_path(r'^forgot_password$', forgot_password.forgot_password_page, name='forgot_password'),
#     re_path(r'^reset_password$', forgot_password.reset_password, name='reset_password'),
                       
#     # Sitemap
#     re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
#     re_path(r'^captcha/', include('captcha.urls')),
]

login/urls.py
from django.urls import  include, re_path, path

from . import views
from django.contrib.auth import views as auth_views
app_name = 'login'
urlpatterns = [
	path('accounts/password_reset/',auth_views.PasswordResetView.as_view(template_name='login/password_reset.html'), name='password_reset'),
    path('accounts/change-password/', auth_views.PasswordChangeView.as_view(template_name='login/password_change.html'), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeView.as_view(template_name='login/password_change.html'), name='password_change_done'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password-reset-confirm/', auth_views.PasswordResetConfirmView.as_view(template_name='login/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset_complete.html'), name='password_reset_complete'),
   
    re_path('login/', include([
        re_path(r'^login_modal$', views.login_modal),
        re_path(r'^login_redirect$', views.login_redirect, name='login_redirect'),
        re_path(r'^login$', views.login_authentication),
        re_path(r'^logout$', views.logout_authentication),

    ])),
    
            ]

yumisrc/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static, settings
from django.contrib.auth import views
from django.urls import path, re_path


urlpatterns = [
    url(r'^search/', include('haystack.urls')),  # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('landpage.urls',namespace='landpage' )),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')), 
    re_path(r'', include('account.urls', namespace='account' )),
    re_path(r'', include('adverts.urls', namespace='adverts' )),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from adverts.models import Advert
from cloudinary.models import CloudinaryField

COUNTY_CATEGORY_TYPES = (
('Kenya', 'Kenya'),
('Lesotho', 'Lesotho'),
('Liberia', 'Liberia'),
('Libya', 'Libya'),
('Madagascar', 'Madagascar'),
('Malawi', 'Malawi'),
('Mali', 'Mali'),
('Mauritania', 'Mauritania'),
('Mauritius', 'Mauritius'),
('Morocco', 'Morocco'),
('Mozambique', 'Mozambique'),

)
TOWN_CATEGORY_TYPES = (
('Nairobi','Nairobi'),
('Niger', 'Niger'),
('Nigeria', 'Nigeria'),
('Rwanda', 'Rwanda'),
('Sao Tome and Principe', 'Sao Tome and Principe'),
('Senegal', 'Senegal'),
('Seychelles', 'Seychelles'),
('Sierra Leone', 'Sierra Leone'),
('Somalia', 'Somalia'),
('South Africa', 'South Africa'),
('South Sudan', 'South Sudan'),
('Sudan', 'Sudan'),
('Tanzania', 'Tanzania'),
('Togo', 'Togo'),
('Tunisia', 'Tunisia'),
('Uganda', 'Uganda' ),
('Zambia', 'Zambia' )
)

class PrivateMessage(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=127)
    text = models.TextField()
    sent_date = models.DateField(auto_now_add=True, null=True)
    to_address = models.CharField(max_length=255)
    from_address = models.CharField(max_length=255)
    
    def __str__(self):
        return "From: " + self.from_address + " To: " + self.to_address + " Title: " + self.title
    
    class Meta:
        db_table = 'at_private_messages'



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic =  CloudinaryField('image', blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    title = models.CharField(max_length=4, blank=True, null=True)
    county = models.CharField(max_length=127, choices=COUNTY_CATEGORY_TYPES,  blank=True,null=True,  default='Kenya')
    phone_number = models.IntegerField(blank=True, null=True)
    town = models.CharField(max_length=127, choices=TOWN_CATEGORY_TYPES,  blank=True,null=True,  default='Nairobi')
    saved_ads = models.ManyToManyField(Advert, related_name='user_ads')

    def create_user_profile(sender, **kwargs):
            if kwargs['created']:
                UserProfile.objects.create(user=kwargs['instance'])

    post_save.connect(create_user_profile, sender=User)

    @property
    def total_saved(self):
        self.saved_ads.count()
    
    def __str__(self):
        return self.user.first_name + " " + \
                          self.user.last_name 
  

    

account/views/mail.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
import datetime
from account.models import PrivateMessage
from account.forms import PrivateMessageForm
from django.core.mail import send_mail
from django.contrib.auth.models import User
from yumisrc.secret_settings import EMAIL_HOST_USER
from django.core.mail import send_mass_mail
from django.core.mail.message import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context

@login_required(login_url='/home')
def mail_page(request):
    try:
        email = request.user.email
        messages = PrivateMessage.objects.filter(to_address=email)
    except PrivateMessage.DoesNotExist:
        messages = None
    
    return render(request, 'account/mail/view.html',{
        'messages': messages,
        'user': request.user,
        'tab': 'inbox',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })




@login_required()
def send_private_message(request):
    response_data = {'status' : 'failed', 'message' : 'unknown error'}
    if request.is_ajax():
        if request.method == 'POST':
            title = request.POST['title']
            text = request.POST['message']
            email = request.POST['email']
            
            # Validate email exists on system.
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                response_data = {'status' : 'failure', 'message' : 'email does not exist in our system'}
                return HttpResponse(json.dumps(response_data), content_type="application/json")

            PrivateMessage.objects.create(
                title=title,
                text=text,
                to_address=email,
                from_address=request.user.email,
            ).save()

            response_data = {'status' : 'success', 'message' : 'private message sent'}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required()
def view_private_message(request):
    response_data = {'status' : 'failed', 'message' : 'unknown error'}
    if request.is_ajax():
        if request.method == 'POST':
            message_id = int(request.POST['message_id'])
            try:
                message = PrivateMessage.objects.get(id=message_id)
            except PrivateMessage.DoesNotExist:
                message = None
            
            form = PrivateMessageForm(instance=message)
            return render(request, 'account/mail/modal.html',{
                'form': form,
                'user': request.user,
                'tab': 'inbox',
                'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
                'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
            })


@login_required()
def delete_private_message(request):
    response_data = {'status' : 'failed', 'message' : 'unknown error'}
    if request.is_ajax():
        if request.method == 'POST':
            message_id = int(request.POST['message_id'])
            try:
                message = PrivateMessage.objects.get(
                    id=message_id,
                ).delete()
            except PrivateMessage.DoesNotExist:
                message = None
            
            response_data = {'status' : 'success', 'message' : 'deleted private message'}
    return HttpResponse(json.dumps(response_data), content_type="application/json")



def email_users(request):
    # users=User.objects.all().values_list('email',flat=True)
    users = User.objects.all()
    for user in users:
        subject = 'Welcome to Leadership and development Academy '
        msg = f'testtesttest {user.first_name} {user.first_name} '
        from_email = 'onboarding@leadershipacademyafrica.com'
        messages = [(subject,msg,from_email,[user.email])]
        send_mass_mail((messages),fail_silently=False)
    return  HttpResponse("welcome email")


# def email_users(request):

#     users = User.objects.all()
#     for user in users:
#         # context = Context ({'first_name': user.first_name, 'last_name': user.last_name})
#         subject ='Welcome to Leadership and development Academy '
#         from_email = 'onboarding@leadershipacademyafrica.com'
#         to = [user.email]
#         message =render_to_string('account/mail/email_template.html')
#         messages = EmailMultiAlternatives (subject,text_alternative ,from_email,[user.email])
#         messages.attach_alternative(html_alternative, "text/html")
#     #     send_mass_mail((messages),fail_silently=False)
#     # return  HttpResponse("welcome email")

account/views/profile.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
from django.shortcuts import render,redirect, get_object_or_404
from account.forms import UserProfileForm
from registration.form import RegisterForm
from django.db import transaction
from account.models import *
from adverts.models import *
from django.contrib import messages
from django.utils.translation import gettext as _




@login_required(login_url='/home')
def view_profile(request):
    adverts = Advert.objects.filter(user_id=request.user.id)   
    return render(request, 'profile/profile_home.html',{
        'adverts':'adverts',
        'tab': 'profile',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })
@login_required(login_url ='login:login_redirect')
def save_ads(request, id):
    if request.method == 'POST':
        advert = get_object_or_404(Advert, id =id)
        userprofile = request.user.userprofile
        userprofile.saved_ads.add(advert)
        messages.success(request, _('Your ad was saved!'))
    return HttpResponse("You saved")

@login_required()
def update_user(request):
    response_data = {'status' : 'failed', 'message' : 'unknown deletion error'}
    if request.is_ajax():
        if request.method == 'POST':
            form = RegisterForm(instance=request.user, data=request.POST)
            if form.is_valid():
                form.instance.username = form.instance.email
                form.save()
                response_data = {'status' : 'success', 'message' : 'updated user'}
            else:
                response_data = {'status' : 'failed', 'message' : json.dumps(form.errors)}
    return HttpResponse(json.dumps(response_data), content_type="application/json")

@login_required()
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':

        # user_form = RegisterForm(request.POST,instance=request.user)
        profile_form = UserProfileForm(request.POST,files=request.FILES, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect ('account:view_my_ads', user_id = request.user.id )
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        profile_form = UserProfileForm(instance=request.user.client)
    return render(request, 'profile/edit_profile.html', {
        # 'user_form': user_form,
        'profile_form': profile_form,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })


   

@login_required(login_url ='login:login_redirect')
def view_my_ads(request, user_id):
    adverts = Advert.objects.filter(user_id = request.user.id) 
    userprofile = UserProfile.objects.get(user=request.user)
    total_saved = userprofile.total_saved

    return render(request,'profile/myadds.html', context ={  
       
        'total_saved':total_saved,
        'adverts': adverts,
        'user_id ': user_id, 
        'tab': 'adverts',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

@login_required(login_url ='login:login_redirect')
def view_messages(request):
   
    return render(request, 'profile/messages.html',{
        
        'tab': 'messages',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

@login_required(login_url ='login:login_redirect')
def view_who_watched(request):
   
    return render(request, 'profile/view_who_watched.html',{
        
        'tab': 'favourite',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })


        
   
@login_required(login_url ='login:login_redirect')
def view_settings(request):
   
    return render(request, 'profile/settings.html',{
         
        'tab': 'settings',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

account/templates/profile/deletead.html
{% extends 'base/accountbase.html' %}
{% load static %}
{% block content %}

 <!-- Start Content -->
 <div id="content">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-md-12 col-lg-4 page-sidebar">
                {% include "profile/sidebar.html" %}
            </div>
            <div class="col-lg-8 col-md-12 col-xs-12 page-content">
                    <div class="inner-box">
                      <h2 class="title-2"><i class="fas fa-times"></i> Close account </h2>
                      <p>You are sure you want to close your account?</p>
                  <form action="{% url 'adverts:delete_post' id=advert.id  %}"  method="POST">


                  </form>
                      <br>

                <a  href="{% url 'account:view_my_ads' user_id=request.user.id  %}" class="btn btn-common pt"> <i class="fas fa-pencil-square-o"></i> Cancel</a>

                      <button type="submit" name="confirm_delete" class="btn btn-common pt">Submit</button>
                    </div>
                  </div>
     
          </div>  
        </div>      
      </div>
      <!-- End Content -->
  
{% include "base/jsmodal.html"  %} 
<div id="ajax_response_login"></div>
<div id="ajax_response_register"></div>
<div id="ajax_logout"></div>
<div id="fb-root"></div>
{% endblock content %}

account/templates/profile/myadds.html
{% extends 'base/accountbase.html' %}
{% load static %}
{% block content %}


    <!-- Start Content -->
    <div id="content">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-12 col-lg-4 page-sidebar">
              {% include "profile/sidebar.html" %}
          </div>

          <div class="col-lg-8 col-md-12 col-xs-12 page-content">
            <div class="inner-box">
              <h2 class="title-2"><i class="fas fa-credit-card"></i> My ADS</h2>
              <div class="table-responsive">
                <div class="table-action">
                  <div class="checkbox">
                 <strong>  Total Ads : </strong>
                  </div>
                  <div class="table-search float-right">
                      <div class="row">
                          <div class="col">
                            <div class="card card-body">
                        
                              <form method="get">
                                {{myFilter.form}}
                        
                                <button class="btn btn-primary" type="submit">Search</button>
                              </form>
                        
                            </div>
                          </div>
                          
                        </div>
                    <!-- <div class="form-group row">
                      <label class="mr-2 col-xs-5 control-label text-right">Search <br>
                      </label>
                      <div class="mr-3 col-xs-7 searchpan">
                        <input class="form-control" id="filter" type="text">
                      </div>
                    </div> -->
                  </div>
                </div>
                <table class="table table-striped table-bordered add-manage-table">
                  <thead>
                    <tr>
                      <th data-type="numeric"></th>
                      <th>Photo</th>
                      <th>Ad Details</th>{{total_saved}}
                      <th>Price</th>
                      <th>Option</th>
                    </tr>
                  </thead>
                  
                  {% for advert in adverts %}
                  <tbody>
                    <tr>
                      <td class="add-img-selector">
                        <div class="checkbox">
                          <label>
                            <input type="checkbox">
                          </label>
                        </div>
                      </td>
                      <td class="add-img-td">
                          <!-- {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %} -->
                        <!-- <a href="{% url 'account:save_ads' user_id=request.user.id  %}"> -->
                          <img class="img-fluid" src="{{advert.image.url}}" alt="img">
                        </a>
                      </td>
                      <td class="ads-details-td">
                          <!-- {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %} -->
                        <h4><a href="{% url 'adverts:advert_detail' id=advert.id slug=advert.slug %} "> {{advert.name}}</a></h4>
                        <p> <strong> Posted On </strong>:
                          {{advert.pub_date}}</p>
                          <p> <strong>Ad Category:</strong> {{advert.category}} </p>

                        <p> <strong>Located In:</strong> {{advert.location}} </p>
                      </td>
                      <td class="price-td">
                        <strong>{{advert.price}}</strong>
                      </td>
                      <td class="action-td">
                        <p><a  href="{% url 'adverts:update_post' id=advert.id  %}" class="btn btn-primary btn-xs"> <i class="fas fa-pencil-square-o"></i> Edit</a></p>
                        <p><a class="btn btn-info btn-xs"> <i class="fas fa-share-square-o"></i> Share</a></p>
                        <p><a  href="{% url 'adverts:delete_post' id=advert.id  %}"  class="btn btn-danger btn-xs"> <i class=" fas fa-trash"></i> Delete</a></p>
                      </td>
                    </tr>
              
                  </tbody>
              
                  {% endfor %}

                 
                 
      
              
                </table>

            

            
              </div>               
            </div>
         
          </div>
        </div>  
      </div>      
    </div>
    <!-- End Content -->

    {% include "base/jsmodal.html"  %} 
  <div id="ajax_response_login"></div>
  <div id="ajax_response_register"></div>
  <div id="ajax_logout"></div>
  <div id="fb-root"></div>
{% endblock content %}

account/templates/profile/savedads.html
{% extends 'base/accountbase.html' %}
{% load static %}
{% block content %}


    <!-- Start Content -->
    <div id="content">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-12 col-lg-4 page-sidebar">
              {% include "profile/sidebar.html" %}
          </div>

          <div class="col-lg-8 col-md-12 col-xs-12 page-content">
            <div class="inner-box">
              <h2 class="title-2"><i class="fas fa-credit-card"></i> SAVED ADS</h2>
              <div class="table-responsive">
                <div class="table-action">
                  <div class="checkbox">
                 <strong>  Total Saved Ads : </strong>
                  </div>
                  <div class="table-search float-right">
                    <div class="form-group row">
                      <label class="mr-2 col-xs-5 control-label text-right">Search <br>
                      </label>
                      <div class="mr-3 col-xs-7 searchpan">
                        <input class="form-control" id="filter" type="text">
                      </div>
                    </div>
                  </div>
                </div>
                <h5> You dont have any Ads <span> <a class="btn  btn-primary btn-xs" href="{% url 'adverts:post_ad' %}"><span class="fas fa-plus-circle"></span> Post an Ad</a></span></h5>

                <!-- <table class="table table-striped table-bordered add-manage-table">
                  <thead>
                    <tr>
                      <th data-type="numeric"></th>
                      <th>Photo</th>
                      <th>Adds Details</th>
                      <th>Price</th>
                      <th>Option</th>
                    </tr>
                  </thead>
                  {% if adverts %} 
                  {% for advert in adverts %}
                  <tbody>
                    <tr>
                      <td class="add-img-selector">
                        <div class="checkbox">
                          <label>
                            <input type="checkbox">
                          </label>
                        </div>
                      </td>
                      <td class="add-img-td">
                        <a href="">
                          <img class="img-fluid" src="assets/img/item/img-1.jpg" alt="img">
                        </a>
                      </td>
                      <td class="ads-details-td">
                        <h4><a href=""> {{advert.name}}</a></h4>
                        <p> <strong> Posted On </strong>:
                          {{advert.pub_date}}</p>
                          <p> <strong>Ad Category:</strong> {{advert.category}} </p>

                        <p> <strong>Located In:</strong> {{advert.location}} </p>
                      </td>
                      <td class="price-td">
                        <strong>{{advert.price}}</strong>
                      </td>
                      <td class="action-td">
                        <p><a  href="{% url 'adverts:update_post' id=advert.id  %}" class="btn btn-primary btn-xs"> <i class="fas fa-pencil-square-o"></i> Edit</a></p>
                        <p><a class="btn btn-info btn-xs"> <i class="fas fa-share-square-o"></i> Share</a></p>
                        <p><a  href="{% url 'adverts:delete_post' id=advert.id  %}"  class="btn btn-danger btn-xs"> <i class=" fas fa-trash"></i> Delete</a></p>
                      </td>
                    </tr>
              
                  </tbody>
              
                  {% endfor %}

                  {% else %}
                  
                 
      
               {% endif %}
                </table> -->

            

            
              </div>               
            </div>
         
          </div>
        </div>  
      </div>      
    </div>
    <!-- End Content -->

    {% include "base/jsmodal.html"  %} 
  <div id="ajax_response_login"></div>
  <div id="ajax_response_register"></div>
  <div id="ajax_logout"></div>
  <div id="fb-root"></div>
{% endblock content %}

account/templates/profile/sidebar.html
{% load static %}
<aside>
        <div class="col-lg-12 col-md-12 col-xs-12 text-center" style="box-shadow: 0px 3px 9px 2px rgba(0,0,0,0.21);">
            <br>
            {% if request.user %}
            <div class="sidebar-box">
                <div class="user">
                  <div class="usercontent">
                  
                  </div>
                  {% if user.client.profile_pic %}
                  <figure>
                      <a href="#"><img class="-img-fluid" src="{{user.client.profile_pic.url}}" alt=""></a>
                    </figure>
                    {% else %}
                  <figure>
                    <a href="{% url 'account:update_profile'  %}"><img class="-img-fluid" src="{% static 'assets/img/author/img1.jpg' %}" alt=""></a>
                  </figure>
                  {% endif %}
                </div>
              </div>
            <h4 class="widget-title">{{ user.first_name |upper }} {{user.last_name |upper }} </h4>
            
            <div class="row justify-content-center">

             
             
                    <a class=" btn-sm btn-white  " style=" margin: 3px; " href="{% url 'account:view_messages'  %}" >  
                    <i class="fas fa-home"></i>
                    <span>Account Home</span></a> 

                    <a class="btn-sm btn-white  " style=" margin: 3px; " href="{% url 'account:view_my_ads' user_id=request.user.id  %}" > 
                      <i class="fas fa-store"></i>
                      <span>My Ads</span></a> 

                      <a class="btn-sm btn-white  " style=" margin: 3px; " href="{% url 'account:view_who_watched'  %}" > 
                          <i class="fas fa-bar-chart"></i>
                          <span>My Ads Statistics</span></a> 

                      <a class="btn-sm btn-white  " style=" margin: 3px; " href="" > 
                              <i class="fas fa-bookmark "></i>
                        <span>Saved Ads</span></a> 
                      

                      <a class="btn-sm btn-white  " style=" margin: 3px; " href="{% url 'account:view_messages'  %}"  >  
                          <i class="fas fa-envelope"></i>
                          <span>Inbox messages</span></a>

                          <a class="btn-sm btn-white  " style=" margin: 3px; " href="{% url 'landpage:contact_us'  %}" > 
                              <i class="fas fa-phone "></i>
                        <span>Contact Support</span></a> 
                    
              
             
                
                      </div> 
                        <br>
        </div>

        {% endif %}
        <!-- <div class="widget">
          <h4 class="widget-title">Advertisement</h4>
          <div class="inner-box">
            <div class="add-box">
              <img class="img-fluid" src="assets/img/img1.jpg" alt="">
            </div>
          </div>
        </div> -->
      </aside>