account/urls.py
from django.urls import  include, re_path
from account.views import mail
from account.views import profile
from account.views import setting
from account.views import *

app_name = 'account'

urlpatterns = [
    re_path('profile/', include([
        re_path(r'^send_email_message$', mail.email_users),
        re_path(r'^inbox$', mail.mail_page),
        re_path(r'^send_private_message$', mail.send_private_message),
        re_path(r'^view_private_message$', mail.view_private_message),
        re_path(r'^delete_private_message$', mail.delete_private_message),
  
        # re_path(r'^update_user$', profile.update_user),
        re_path(r'^settings$', setting.settings_page),
        re_path(r'^update_password$', setting.update_password),
        re_path(r'^update_profile$', profile.update_profile, name='update_profile'),
        
        re_path(r'^view_profile', profile.view_profile, name ='view_profile'),
        re_path(r'^view_my_ads/(?P<user_id>\d+)/$', profile.view_my_ads, name='view_my_ads'),
        re_path(r'^saved_ads/(?P<id>\d+)/$', profile.save_ads, name='saved_ads'),
        re_path(r'^view_message$', profile.view_messages, name= 'view_messages'),
        re_path(r'^view_who_watched$', profile.view_who_watched, name='view_who_watched'),
        re_path(r'^view_settings$', profile.view_settings, name='view_settings'),

        ]))
]

adverts/urls.py
from django.urls import re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'adverts'


urlpatterns = [
    re_path('Ads/', include([
        re_path(r'^post_ad/$', views.post_ad, name='post_ad'),
        re_path(r'^$', views.adverts_list, name='adverts_list'),
        re_path(r'^edit_ad/(?P<id>\d+)/$', views.update_post, name='update_post'), 
        re_path(r'^delete_ad/(?P<id>\d+)/$', views.delete_post, name='delete_post'), 
        re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.advert_detail, name='advert_detail'), 
        re_path(r'^(?P<category_slug>[-\w]+)/$', views.adverts_list_by_category, name='adverts_list_by_category'),
        re_path(r'^likead/(?P<id>\d+)/$', views.like_ad, name='like_ad')


 
   ]))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import  include, re_path, path

from . import views
from django.contrib.auth import views as auth_views
app_name = 'login'
urlpatterns = [
	path('accounts/password_reset/',auth_views.PasswordResetView.as_view(template_name='login/password_reset.html'), name='password_reset'),
    path('accounts/change-password/', auth_views.PasswordChangeView.as_view(template_name='login/password_change.html'), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeView.as_view(template_name='login/password_change.html'), name='password_change_done'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password-reset-confirm/', auth_views.PasswordResetConfirmView.as_view(template_name='login/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset_complete.html'), name='password_reset_complete'),
   
    re_path('login/', include([
        re_path(r'^login_modal$', views.login_modal),
        re_path(r'^login_redirect$', views.login_redirect, name='login_redirect'),
        re_path(r'^login$', views.login_authentication),
        re_path(r'^logout$', views.logout_authentication),

    ])),
    
            ]

yumisrc/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static, settings
from django.contrib.auth import views
from django.urls import path, re_path


urlpatterns = [
    url(r'^search/', include('haystack.urls')),  # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('landpage.urls',namespace='landpage' )),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')), 
    re_path(r'', include('account.urls', namespace='account' )),
    re_path(r'', include('adverts.urls', namespace='adverts' )),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adverts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from cloudinary.models import CloudinaryField
import datetime



from cloudinary.models import CloudinaryField

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = CloudinaryField('image', blank=True, null=True)
  
    

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def adverts_in_category(self):
        return self.adverts.all().count()
        

    def get_absolute_url(self):
        return reverse('adverts:adverts_list_by_category', args=[self.slug])

class Location(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'location'
        verbose_name_plural = 'locations'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adverts:adverts_list_by_location', args=[self.slug])

class Option(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'option'
        verbose_name_plural = 'options'

    def __str__(self):
        return self.name

class Item_condition(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Item_condition'
        verbose_name_plural = 'Item_conditions'

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=150, db_index=True)


    class Meta:
        ordering = ('name', )
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name

class Advert(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='adverts', on_delete=models.CASCADE)
    location = models.ForeignKey(Location, related_name='adverts', on_delete=models.CASCADE)
    option = models.ForeignKey(Option, related_name='adverts', on_delete=models.CASCADE)
    item_condition = models.ForeignKey(Item_condition, related_name='item_condition', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=100, db_index=True)
    price = models.PositiveIntegerField()
    pub_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = CloudinaryField('image')
    available = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, related_name='post_likes')
    accept_terms = models.BooleanField(default=True)
    
    
   



    class Meta:
        ordering = ('-pub_date', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name +'' + 'by' + '' + str(self.user)

    def snippet(self):
        return self.description[:50]


    @property
    def total_likes(self):
        return self.likes.count()
    
    
    

    def get_absolute_url(self):
        return reverse('adverts:advert_detail',  kwargs={"id":self.id, "slug":self.slug})







class Review(models.Model):
    """This class creates an ads reviewing odel."""

    reviewer = models.ForeignKey(
        User,
        related_name='client_review',
        on_delete=models.CASCADE
    )
    adseller = models.ForeignKey(
       User,
        related_name='seller_reviews',
        on_delete=models.CASCADE
    )
    review = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    def reviewer_name(self):
        """This method gets the username of the user reveiwing  advert ."""
        return self.user.username
    
    def __str__(self):
        return self.review + '' + 'by' + '' + str(self.reviewer) + '' + 'for' + ' ' + str(self.adseller)

    

adverts/views.py
import json
from django.db.models import F
from django.utils import timezone
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth.models import User
from adverts.forms import PostadForm, ReviewAdForm
from adverts.models import *
from account.views import profile
from django.contrib import messages
from django.utils.translation import gettext as _
from django.utils.text import slugify
from django.core.paginator import Paginator
from django.urls import reverse_lazy, reverse



@login_required(login_url ='login:login_redirect')
def post_ad(request):
    if request.method == 'POST':
       
        post_form = PostadForm(request.POST, files=request.FILES)
        
        if post_form.is_valid():
            post_form=post_form.save(commit=False)
            post_form.slug = slugify(post_form.name)
            post_form.user=request.user
            post_form.save()
            messages.success(request, _('Your ad was successfully posted!'))
            return redirect('account:view_my_ads', user_id=request.user.id )

        else:
            messages.error(request, _('Please correct the error below.'))
    else:
         post_form = PostadForm(instance=request.user)

    print(post_form.is_valid())
    return render(request, 'listings/postad.html', {
        # 'user_form': user_form,
        'post_form': post_form,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

@login_required(login_url ='login:login_redirect')
def update_post(request, id, ):
    advert = get_object_or_404(Advert, id=id,  )
    post_form = PostadForm(instance=advert, )
    if request.method == 'POST':
       
         # user_form = RegisterForm(request.POST,instance=request.user)
        post_form = PostadForm(request.POST,instance=advert)
        
        if post_form.is_valid():
            # post_form.slug = slugify(post_form.name)
            post_form.user=request.user
            post_form.save()
            messages.success(request, _('Your ad was successfully posted!'))
            return redirect('account:view_my_ads', user_id=request.user.id )

        else:
            messages.error(request, _('Please correct the error below.'))

    
    return render(request, 'listings/postad.html', {
        'post_form': post_form,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })


@login_required(login_url ='login:login_redirect')
def delete_post(request, id, ):
    advert = get_object_or_404(Advert, id=id,  )
    if request.method == 'POST':
        advert.delete()
        return redirect('account:view_my_ads', user_id=request.user.id )
     
    
    return render(request, 'listings/deletead.html', {
        'advert': advert,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })


def like_ad(request, id):
    def like_ad(request, id):
        if request.method == 'POST':
            advert = get_object_or_404(Advert, id=id)
            user = request.user
            advert.likes.add(user)
        messages.success(request, _('Your ad was successfully posted!'))
    return redirect('adverts:advert_detail', id=advert.id, slug=advert.slug )
        
        
    

def adverts_list_by_category(request, category_slug):
    category = None
    categories = Category.objects.all()
    category = Category.objects.filter(slug=category_slug)
    adverts = Advert.objects.filter(available=True)
    paginator = Paginator(adverts, 2)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        adverts = Advert.objects.filter(category=category)
    if page.has_next():
        next_url = f'?page={page.next_page_number()}'
    else:
        next_url = ''

    if page.has_previous():
        prev_url = f'?page={page.previous_page_number()}'
    else:
        prev_url = ''
        

    return render(request, 'listings/advertlist.html',   context = {
        'category': category,
        'categories': categories,
        'adverts' : adverts,
        'page': page, 
        'next_page_url' : next_url,
        'prev_page_url': prev_url,
        'tab': 'listings',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    }) 



def adverts_list(request):
    categories = Category.objects.all()
    adverts = Advert.objects.filter(available=True)
    paginator = Paginator(adverts, 4)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    if page.has_next():
        next_url = f'?page={page.next_page_number()}'
    else:
        next_url = ''

    if page.has_previous():
        prev_url = f'?page={page.previous_page_number()}'
    else:
        prev_url = ''
        

    return render(request, 'listings/advertlist.html',   context = {
        'adverts' : adverts,
        'categories': categories,
        'category':'category',
        'page': page, 
        'next_page_url' : next_url,
        'prev_page_url': prev_url,
        'tab': 'listings',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    }) 

@login_required(login_url ='login:login_redirect')
def advert_detail(request, id, slug):
    advert = get_object_or_404(Advert, id=id , slug=slug, available=True)
    ad_seller = advert.user
    reviews = ad_seller.seller_reviews.all()
    total_likes = advert.total_likes
    print(total_likes)
    new_comment = None
    if request.method == 'POST':
        comment_form = ReviewAdForm(data=request.POST)
        if comment_form.is_valid():

            # Create  object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current review to the advert owner
            new_comment.reviewer = request.user
            new_comment.adseller = ad_seller
            if new_comment.reviewer == new_comment.adseller:
                new_comment = None
                messages.error(request, 'You cannot review yourself')

            else:
                new_comment.save()
                messages.success(request, 'Your review has been published')
    else:
        comment_form = ReviewAdForm(data=request.POST)
    return render( request, 'listings/advertdetail.html', context={
        'advert': advert,
        'reviews': reviews,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    }
      )



    





  

adverts/templates/listings/adsobjects.html
{% load tz %}
{% load humanize %}

{% if adverts %}
{% for advert in adverts %}

  <div class="item-list">
    <div class="row">
      <div class="col-sm-2 no-padding photobox">
        <div class="add-image">
 
          <a href=" {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %}"><img src="{{advert.image.url}}" alt=""></a>
          <span class="photo-count"><i class="fas fa-camera"></i>2</span>
        </div>
      </div>
      <div class="col-sm-7 add-desc-box">
        <div class="add-details">
          <h5 class="add-title"><a href=" {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %}"> {{advert.name}}</a></h5>
          <div class="info">
              <span class="category"> <a href="{{advert.category.get_absolute_url}}"><strong>{{advert.category}}</strong></a></span> in 
              <span class="item-location"><i class="fas fa-map-marker"></i>  {{advert.location}} </span>
            <span class="date">
             Posted on - <i class="fas fa-clock"></i> 
           {{advert.pub_date|naturaltime}}
            </span> 
         
            <span class="category"> Posted by -<a href="#"><strong>  {{advert.user}}</strong> </a></span> 
          </div>
         
          <div class="item_desc">
            <a href=" {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %}"> {{advert.description}}</a>
          </div>
        </div>
      </div>
   
      <div class="col-sm-3 float-right  price-box">
        <h3 class="item-price"> KSH {{advert.price}}</h3>
        <a href=" {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %}" class="btn btn-common2 btn-sm"><i class="fas fa-arrow-right "></i>
        <span>More Detials</span></a> 
        <a href=" {% url 'adverts:advert_detail' id=advert.id slug=advert.slug %}" class="btn btn-common btn-sm"> <i class="fas fa-eye"></i> <span>215</span> </a> 
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="post-promo text-center" style="box-shadow: 1px 1px 53px -23px rgba(0,0,0,0.75); ">
      <h2> No Items posted on Site, Currently </h2>
      <h5>Sell your products online FOR FREE. It's easier than you think !</h5>
      <a href="{% url 'adverts:post_ad' %}" class="btn btn-post btn-common2">Post a Free Ad </a>
      <!-- <div class="item_desc">
          <a href=" #"> <strong>How we work </strong></a>
        </div> -->
    </div>


  {% endif %}
</div>
<!-- Adds wrapper End -->
<div class="col-12">
    <!-- Start Pagination -->
    <div class="pagination-bar">
       <nav>
        <ul class="pagination">
            <li class="page-item "><a class="page-link { if not prev_page_url } disabled { endif }" href="{{ prev_page_url }}">Prev</a></li>
          {% for n in page.paginator.page_range %}
             {% if page.number == n %}

              <li class="page-item"><a class="page-link active" href="?page={{ n }}">{{ n }}</a></li>
              {% elif n > page.number|add:-3 and  n < page.number|add:3  %}
              <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>

              {% endif %}
          {% endfor %}
          <li class="page-item  "><a class="page-link {if not next_page_url } disabled { endif }" href="{{ next_page_url }}">Next</a></li> 

          <!-- <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">4</a></li>
          <li class="page-item"><a class="page-link" href="#"> ...</a></li>
          <li class="page-item  {if not page_url } disabled { endif }"><a class="page-link" href="{{next_page_url}}">Next</a></li> -->
        </ul>
      </nav>
    </div>
    <!-- End Pagination -->

    <div class="post-promo text-center" style="box-shadow: 1px 1px 53px -23px rgba(0,0,0,0.75); ">
   
      
      <h2> Have anything to sell?</h2>
      <h5>Sell your products online FOR FREE. It's easier than you think !</h5>
      <a href="{% url 'adverts:post_ad' %}" class="btn btn-post btn-common2">Post a Free Ad </a>
      <!-- <div class="item_desc">
          <a href=" #"> <strong>How we work </strong></a>
        </div> -->
    </div>
  </div>

adverts/templates/listings/deletead.html
{% extends 'base/accountbase.html' %}
{% load static %}
{% block content %}

 <!-- Start Content -->
 <div id="content">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-md-12 col-lg-4 page-sidebar">
                {% include "profile/sidebar.html" %}
            </div>
            <div class="col-lg-8 col-md-12 col-xs-12 page-content">
                    <div class="inner-box">
                      <h2 class="title-2"> Delete <i class="lnr lnr-pointer-right"></i> {{advert.name}} </h2>
                      <p>You are sure you want to delete  <strong> <h5>{{advert.name}}?</h5> </strong>   </p>
                      <form action="{% url 'adverts:delete_post' id=advert.id  %}"  method="POST">

                      {% csrf_token %}

                      <a  href="{% url 'account:view_my_ads' user_id=request.user.id  %}" class="btn btn-common pt"> <i class="fas fa-times"></i>Cancel</a>

                      <button type="submit" name="confirm_delete" class="btn btn-danger pt">Delete</button>

                  </form>
                      <br>

                    </div>
                  </div>
     
          </div>  
        </div>      
      </div>
      <!-- End Content -->
  
{% include "base/jsmodal.html"  %} 
<div id="ajax_response_login"></div>
<div id="ajax_response_register"></div>
<div id="ajax_logout"></div>
<div id="fb-root"></div>
{% endblock content %}

adverts/templates/listings/postad.html
{% extends 'base/advertbase.html' %}
{% load static %}
{% block content %}
{% block title %} YUMI | Post Ad {% endblock %}

  <!-- Content section Start -->
  <section id="content">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12 col-lg-10">
          <div class="row page-content">
              <h4 class="widget-title">Ad Detail</h4>
             
                <div class="container">
                <div  class="row justify-content-center">
         

            </div>
            <!-- {{ post_form.media }}
 <form action = "" method = "post"> 
                  {% csrf_token %} 
                  {{ post_form.as_p }} 
                  <input type="submit" value="Submit"> 
              </form>  -->
              <div id="error_box" name="error_box" class="alert alert-danger alert-dismissable" hidden="true">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  ERROR: This is to be filled in by the "print_error" function. If you see this message that means there's an error with your javascript somewhere.
              </div>
            {% include "listings/postform.html" with post_form=post_form %}
          

          </div>


        </div>
      </div>
    </div>
  </div>
  </section>
  <!-- Content section End -->
  {% include "base/js.html"  %}

  <div id="ajax_logout"></div>
      {% endblock content  %}

adverts/templates/listings/postform.html
<form action="" method="post" enctype="multipart/form-data" name="post_form" id="post_form"> 
    {% csrf_token %} 

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="row ">
                    <div class="col-lg-6">
      <div class="form-group mb-3">
        <label class="control-label">Ad Title</label>
        <input style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);"  class="form-control input-md" name="name" placeholder="Title"  required type="text" id="id_name">
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group mb-3">
        <label class="control-label">Item Price</label>
        <input style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);"  class="form-control input-md" name="price" id="id_price" placeholder="price" type="number" min="1"  >
      </div>
    </div>
</div>
</div>
<div class="row justify-content-center">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-10 ">
    
        <div class="form-group mb-3">
                <label class="control-label">Ad Description</label>
                <input style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);" rows="5" class="form-control input-md" name="description" id="id_description" placeholder="Maximum 500 words " type="text">
              </div>
            </div>
          

</div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="row ">
                    <div class="col-lg-3">
                            <div class="form-group" >
                                    <label class="control-label">Ad Category</label>
                              <div style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);">
                          {{ post_form.category}}
                                 </div>
                                                   
                                     </div>
                        </div>
                        <div class="col-lg-3">
                                <div class="form-group" >
                                        <label class="control-label">Ad Location</label>
                                  <div style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);">
                              {{ post_form.location}}
                                     </div>
                                                       
                                         </div>
                            </div>
                <div class="col-lg-3">
                        <div class="form-group" >
                                <label class="control-label">Item Condition</label>
                          <div style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);">
                      {{ post_form.item_condition}}
                             </div>
                                               
                                 </div>
                    </div>
                    <div class="col-lg-3">
                            <div class="form-group" >
                                    <label class="control-label">Delivery Option</label>
                              <div style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.16);">
                          {{ post_form.option}}
                                 </div>
                                                   
                                     </div>
                        </div>
                </div>
            </div>
 
 
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="row ">
              <div class="col-lg-6">
                  <div class="form-group md-3">
                      <section  id="editor">
                        <div id="summernote">
                        </div>
                      </section>
                    </div>
                  
                    
                  <span class="btn btn-primary btn-file">
                                                        <span class="fileinput-new">Upload Ad Picture</span>
                                                     
                                                        <input id="id_image" name="image" type="file" onchange="loadFile(event)">
                                          
                                                      </span>

                  
                    </div>
              <div class="col-lg-6 ">

               
                      <div class="features-box wow fadeInDownQuick" data-wow-delay="0.3s">
                  
                          <p>
                              
                         <strong><i class="lnr lnr-map-marker"></i> Location: </strong> This is the curent location of the item.

                        </p>
                        <p>
                            <strong><i class="lnr lnr-car"></i> Option: </strong> Select how the item can be delivered to the buyer. 

                        </p>
                        </div>
                   
                
                  <div class="tg-checkbox mb-2 ">
                      <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="accept_terms" class="required checkbox form-control" id="id_accept_terms" checked="">                        <label class="custom-control-label" for="tg-agreetermsandrules">I agree to all <a href="javascript:void(0);">Terms of Use &amp; Posting Rules</a></label>
                      </div>
                    </div>
                   
<div class="send-btn text-center">
        <button type="submit" class="btn btn-primary "  value="Submit" accept="image/*">Save changes</button>
      </div>
                  </div>

               
    </div>
  </div>
</form>
  

adverts/templates/listings/unused.html
<!-- {% if page.object_list %}
{% for advert in page.object_list %} -->

adverts/templates/listings/updatead.html
{% extends 'base/advertbase.html' %}
{% load static %}
{% block content %}
{% block title %} YUMI | Update Ad {% endblock %}

  <!-- Content section Start -->
  <section id="content">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12 col-lg-10">
          <div class="row page-content">
              <h4 class="widget-title">Ad Detail</h4>
             
                <div class="container">
                <div  class="row justify-content-center">
         

            </div>
            <!-- {{ post_form.media }}
 <form action = "" method = "post"> 
                  {% csrf_token %} 
                  {{ post_form.as_p }} 
                  <input type="submit" value="Submit"> 
              </form>  -->
            {% include "listings/postform.html" with post_form=post_form %}


          </div>


        </div>
      </div>
    </div>
  </div>
  </section>
  <!-- Content section End -->
  {% include "base/js.html"  %}}

  <div id="ajax_logout"></div>
      {% endblock content %}