account/urls.py
from django.urls import  include, re_path
from account.views import mail
from account.views import profile
from account.views import setting
from account.views import *

app_name = 'account'

urlpatterns = [
    re_path('profile/', include([
        re_path(r'^send_email_message$', mail.email_users),
        re_path(r'^inbox$', mail.mail_page),
        re_path(r'^send_private_message$', mail.send_private_message),
        re_path(r'^view_private_message$', mail.view_private_message),
        re_path(r'^delete_private_message$', mail.delete_private_message),
  
        # re_path(r'^update_user$', profile.update_user),
        re_path(r'^settings$', setting.settings_page),
        re_path(r'^update_password$', setting.update_password),
        re_path(r'^update_profile$', profile.update_profile, name='update_profile'),
        
        re_path(r'^view_profile', profile.view_profile, name ='view_profile'),
        re_path(r'^view_my_ads/(?P<user_id>\d+)/$', profile.view_my_ads, name='view_my_ads'),
        re_path(r'^saved_ads/(?P<id>\d+)/$', profile.save_ads, name='saved_ads'),
        re_path(r'^view_message$', profile.view_messages, name= 'view_messages'),
        re_path(r'^view_who_watched$', profile.view_who_watched, name='view_who_watched'),
        re_path(r'^view_settings$', profile.view_settings, name='view_settings'),

        ]))
]

adverts/urls.py
from django.urls import re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'adverts'


urlpatterns = [
    re_path('Ads/', include([
        re_path(r'^post_ad/$', views.post_ad, name='post_ad'),
        re_path(r'^$', views.adverts_list, name='adverts_list'),
        re_path(r'^edit_ad/(?P<id>\d+)/$', views.update_post, name='update_post'), 
        re_path(r'^delete_ad/(?P<id>\d+)/$', views.delete_post, name='delete_post'), 
        re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.advert_detail, name='advert_detail'), 
        re_path(r'^(?P<category_slug>[-\w]+)/$', views.adverts_list_by_category, name='adverts_list_by_category'),
        re_path(r'^likead/(?P<id>\d+)/$', views.like_ad, name='like_ad')


 
   ]))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

landpage/urls.py
from django.urls import include
from django.urls import path, re_path
from . import views
# from django.contrib.sitemaps.views import sitemap
# from .sitemaps import StaticViewSitemap

# sitemaps = {
#     'static': StaticViewSitemap,
# }
app_name = 'landpape'
urlpatterns = [

     #homepages 
     #nologing in required
    re_path(r'^land_page$',views.land_page, name='land_page'),
    re_path(r'^home$', views.land_page, name='home'),
    re_path(r'^welcome/$', views.welcome, name='welcome'),
    re_path(r'^aboutus$', views.about_us, name='about_us'),
    re_path(r'^faqs$', views.faqs, name='faqs'),
    re_path(r'^pricingtable$', views.pricingtable, name='pricingtable'),
    re_path(r'^contactus$', views.contact_us, name='contact_us'), 
  

    
    # re_path(r'^edit/', views.edit, name='edit'),
                  
#     # Off-Convas Stuff
#     re_path(r'^terms$', terms.terms_page, name='terms'),
#     re_path(r'^privacy', privacy.privacy_page, name='privacy'),
#     re_path(r'^forgot_password$', forgot_password.forgot_password_page, name='forgot_password'),
#     re_path(r'^reset_password$', forgot_password.reset_password, name='reset_password'),
                       
#     # Sitemap
#     re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
#     re_path(r'^captcha/', include('captcha.urls')),
]

login/urls.py
from django.urls import  include, re_path, path

from . import views
from django.contrib.auth import views as auth_views
app_name = 'login'
urlpatterns = [
	path('accounts/password_reset/',auth_views.PasswordResetView.as_view(template_name='login/password_reset.html'), name='password_reset'),
    path('accounts/change-password/', auth_views.PasswordChangeView.as_view(template_name='login/password_change.html'), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeView.as_view(template_name='login/password_change.html'), name='password_change_done'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password-reset-confirm/', auth_views.PasswordResetConfirmView.as_view(template_name='login/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset_complete.html'), name='password_reset_complete'),
   
    re_path('login/', include([
        re_path(r'^login_modal$', views.login_modal),
        re_path(r'^login_redirect$', views.login_redirect, name='login_redirect'),
        re_path(r'^login$', views.login_authentication),
        re_path(r'^logout$', views.logout_authentication),

    ])),
    
            ]

registration/urls.py
from django.conf.urls import  include, url
from . import views

app_name = 'registration'
urlpatterns = [
    url(r'^register_modal$', views.register_modal),
    url(r'^register$', views.register),
    url(r'^redirected-register$', views.redirectedregister, name='redirectedregister'),
]

yumisrc/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static, settings
from django.contrib.auth import views
from django.urls import path, re_path


urlpatterns = [
    url(r'^search/', include('haystack.urls')),  # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('landpage.urls',namespace='landpage' )),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')), 
    re_path(r'', include('account.urls', namespace='account' )),
    re_path(r'', include('adverts.urls', namespace='adverts' )),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adverts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from cloudinary.models import CloudinaryField
import datetime



from cloudinary.models import CloudinaryField

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = CloudinaryField('image', blank=True, null=True)
  
    

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def adverts_in_category(self):
        return self.adverts.all().count()
        

    def get_absolute_url(self):
        return reverse('adverts:adverts_list_by_category', args=[self.slug])

class Location(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'location'
        verbose_name_plural = 'locations'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('adverts:adverts_list_by_location', args=[self.slug])

class Option(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'option'
        verbose_name_plural = 'options'

    def __str__(self):
        return self.name

class Item_condition(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Item_condition'
        verbose_name_plural = 'Item_conditions'

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=150, db_index=True)


    class Meta:
        ordering = ('name', )
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name

class Advert(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='adverts', on_delete=models.CASCADE)
    location = models.ForeignKey(Location, related_name='adverts', on_delete=models.CASCADE)
    option = models.ForeignKey(Option, related_name='adverts', on_delete=models.CASCADE)
    item_condition = models.ForeignKey(Item_condition, related_name='item_condition', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=100, db_index=True)
    price = models.PositiveIntegerField()
    pub_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = CloudinaryField('image')
    available = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, related_name='post_likes')
    accept_terms = models.BooleanField(default=True)
    
    
   



    class Meta:
        ordering = ('-pub_date', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name +'' + 'by' + '' + str(self.user)

    def snippet(self):
        return self.description[:50]


    @property
    def total_likes(self):
        return self.likes.count()
    
    
    

    def get_absolute_url(self):
        return reverse('adverts:advert_detail',  kwargs={"id":self.id, "slug":self.slug})







class Review(models.Model):
    """This class creates an ads reviewing odel."""

    reviewer = models.ForeignKey(
        User,
        related_name='client_review',
        on_delete=models.CASCADE
    )
    adseller = models.ForeignKey(
       User,
        related_name='seller_reviews',
        on_delete=models.CASCADE
    )
    review = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    def reviewer_name(self):
        """This method gets the username of the user reveiwing  advert ."""
        return self.user.username
    
    def __str__(self):
        return self.review + '' + 'by' + '' + str(self.reviewer) + '' + 'for' + ' ' + str(self.adseller)

    

adverts/forms.py
from django.db import models
from django import forms
from django.conf import settings
from django.forms import ModelForm
from django.contrib.auth.models import User
from adverts.models import *
import datetime
from django.forms import ModelForm, Textarea, TextInput, NumberInput, FileField, CheckboxInput, Select 
# from django.forms.extras.widgets import Select, SelectDateWidget
from pyuploadcare.dj.models import ImageGroupField, ImageField
from cloudinary.forms import CloudinaryFileField


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

        widgets = {
            'first_name': TextInput(attrs={'class': u'form-control','placeholder': u'Enter First Name', 'required': True}),
            'last_name': TextInput(attrs={'class': u'form-control','placeholder': u'Enter Last Name', 'required': True}),
            'email': TextInput(attrs={'class': u'form-control','placeholder': u'Enter Email', 'required': True}),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name is not None and first_name is not '':
            return first_name
        else:
            raise forms.ValidationError("Cannot be blank")

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name is not None and last_name is not '':
            return last_name
        else:
            raise forms.ValidationError("Cannot be blank")

    def clean_email(self):
        email = self.cleaned_data['email']
        if email is not None and email is not '':
            return email
        else:
             raise forms.ValidationError("Cannot be blank")

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        
       
        try:
            email = cleaned_data.get("email")
            user = User.objects.get(email=email)
            if user != self.instance:
                raise forms.ValidationError("Email already exists")
        except User.DoesNotExist:
            pass

class PostadForm(forms.ModelForm):
    image = CloudinaryFileField(required=False,

        options = {
            'crop': 'thumb',
            'width': 200,
            'height': 200,
            'folder': 'item profile'
       },
    )
    class Meta:
        model = Advert
        fields = { 'name', 'description', 'price', 'location', 'category',  'item_condition','accept_terms', 'option', 'image'}
        labels = {
            'name' :'name',
            'accept_terms': 'accept_terms',
            'description' : 'description',
            'price': 'price',
            'location' : 'location',
            'category': 'category',
            'item_condition': 'item_condition', 
            'option': 'option',
          
            
     }


    def clean_price(self):
        price = self.cleaned_data['price']
        print(price)
        if price < 1 or price is "":
            raise forms.ValidationError("Item Price can not be blank")
        else:
            return price
            
    
class ReviewAdForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['review']
        
        # widgets = {'reviewer': forms.HiddenInput(),'adseller': forms.HiddenInput()}

                   
     
        

adverts/templates/base/advertnav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-inverse fixed-top scrolling-navbar" style="box-shadow: 2px 4px 13px -1px rgba(255,102,13,0.12);">
	<div class="container">
	  <div class="theme-header clearfix">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-toggle="collapse" aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			<span class="lni-menu"></span>
			<span class="lni-menu"></span>
			<span class="lni-menu"></span>
		  </button>

                
		
			<a href="{% url 'landpage:land_page' %}"><img class="navbar-brand" src="{% static 'assets/img/logo0.png' %}" style="width:200px; height:70px;" alt="yumilogo"></a>

			 
		</div>
 		
		<div class="collapse navbar-collapse" id="main-navbar">
		  <ul class="navbar-nav mr-auto w-100 justify-content-end">
			  <li class="nav-item">
				  <a class="nav-link"  href="{% url 'landpage:land_page' %}">
				   Home
				  </a>
		  
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'adverts:adverts_list' %}">
			 Listings 
			  </a>
			</li>
			<li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				  About 
			  </a>
			  <ul class="dropdown-menu">
				<li><a class="dropdown-item"  href="{% url 'landpage:about_us' %}">About Us</a></li>
				<li><a class="dropdown-item" href="{% url 'landpage:pricingtable' %}">Subscription</a></li>
				
				<!-- <li><a class="dropdown-item" href="ads-details.html">Ads Details</a></li>
				<li><a class="dropdown-item" href="post-ads.html">Ads Post</a></li> -->
				<!-- <li><a class="dropdown-item" href="404.html">404</a></li> -->
				<li><a class="dropdown-item" href="{% url 'landpage:faqs' %}">Faqs</a></li>
				<li><a class="dropdown-item" href="{% url 'landpage:contact_us' %}">Contact us</a></li>

			  </ul>
			</li>
			<!-- <li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Blog
			  </a>
			  <ul class="dropdown-menu">
				<li><a class="dropdown-item" href="blog.html">Blog - Right Sidebar</a></li>
				<li><a class="dropdown-item" href="blog-left-sideba.html">Blog - Left Sidebar</a></li>
				<li><a class="dropdown-item" href="blog-full-width.html"> Blog full width </a></li>
				<li><a class="dropdown-item" href="blog-details.html">Blog Details</a></li>
			  </ul>
			</li> -->
					 
	
				{% if request.user.is_authenticated %}
			<li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<i class="lnr lnr-user"></i>Welcome {{user.first_name}} 
			  </a>
			  <ul class="dropdown-menu">
				<li><a class="dropdown-item" href="{% url 'account:view_messages'  %}"><i class="lnr lnr-home"></i> Account Home</a></li>
				<li><a class="dropdown-item" href="{% url 'account:view_my_ads' user_id=request.user.id  %}"><i class="lnr lnr-store"></i> My Ads</a></li>
				<li><a class="dropdown-item" href="{% url 'account:view_who_watched'  %}"><i class="lnr lnr-enter"></i>My Ads statistics </a></li>
				<li><a class="dropdown-item" href="#"><i class="lnr lnr-file-add"></i>Saved Ads</a></li>
				<li><a class="dropdown-item " onclick="ajax_logout();" ><i class="lnr lnr-cross"></i>logout</a></li>
	
			</ul>
			</li>
			{% else %}
			<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<i class="lnr lnr-user"></i>My Account
					</a>
					<ul class="dropdown-menu">
							<li><a class="dropdown-item" href="{% url 'login:login_redirect' %}"><i class="lnr lnr-lock"></i> Log In</a></li>
							<li><a class="dropdown-item"  href="{% url 'registration:redirectedregister' %}"><i class="lnr lnr-user"></i> Signup</a></li>
				
					</ul>
				</li>

				{% endif %}
			<li class="postadd">
			  <a class="btn  btn-primary" href="{% url 'adverts:post_ad' %}"><span class="fas fa-plus-circle"></span> Post an Ad</a>
			</li>
		  </ul>
		</div>
	  </div>
	</div>
	<div  class="mobile-menu" data-logo="{% static 'assets/img/logo0.png' %}"  alt="yumilogo"></div>

	<!-- <div class="mobile-menu" data-logo="assets/img/logo.png"></div> -->
	</nav>
	

     <!-- Login Modal -->
     <div class="modal fade" id="login_modal" tabindex="-1" role="dialog">
				<div class="modal-dialog modal-login" role="document">
					<div class="modal-content">
						<div class="card card-signup card-plain">
							<div class="modal-header">
								<div class="card-header card-header-primary text-center">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="material-icons">clear</i></button>
									<!-- <a><img src="static/img/logo3.png" alt="" style="width:80px; height:80px "></a> -->

									 <div class="social-line">
												<h3 class="modal-title" id="myModalLabel">Student Login</h3>
										<!-- <a href="#pablo" class="btn btn-just-icon btn-link">
											<i class="fa fa-facebook-square"></i>
										</a>
										<a href="#pablo" class="btn btn-just-icon btn-link">
											<i class="fa fa-twitter"></i>
										</a>
										<a href="#pablo" class="btn btn-just-icon btn-link">
											<i class="fa fa-google-plus"></i>
										</a> -->
									</div> 
								</div>
							</div>
							<br>
							<br>
							<div class="modal-body">

					 <form method="post"
										action='/login'
											name="loginForm">


											<div class="form-group">
														<div class="input-group">
															<div class="input-group-prepend">
																<span class="input-group-text">
																	<i class="material-icons">mail</i>
																</span>
															</div>
															<input type="text" class="form-control" name="login_username" id="login_username" placeholder="Enter Email" autocorrect="off" autocapitalize="none">

														</div>
													</div>


											<div class="form-group">
														<div class="input-group">
															<div class="input-group-prepend">
																<span class="input-group-text">
																	<i class="material-icons">lock_outline</i>
																</span>
															</div>
															<input type="password" class="form-control" name="login_password" id="login_password" placeholder="Enter Password">

														</div>
													</div>
													<br>
													<div class="modal-footer justify-content-center">
										<button onclick="ajax_authenticate();"
																type="button"
																class="btn btn-primary btn-round">Sign in
									</button> 
									<a href="/forgot_password">Forgot Password</a>
									<br>   <br>    <br>   <br>
								</div>
							</div>
					
						</form>
					
						</div>
					</div>
				</div>
			</div>
			<!--  End of Login Modal -->
			<div id="ajax_logout"></div>

adverts/templates/base/js.html
{% load static%}
<script>
/**
 *  Function will call AJAX function to load the particular course preview.
 */
function ajax_popup_course_preview(course_id)
{
    var url = 'course_preview_modal';
    $.ajax( url, {
        data: {
           'course_id': course_id,
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            $('#ajax_response_course_preview').html(result); // Update UI.
            $('#course_preview_modal').modal();               // Unhide view.
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
       }
    });
}
        
/**
 *  Function will call AJAX function to load the login modal.
 */
function ajax_popup_login()
{
    var url = 'login_modal';
            
    $.ajax( url, {
        data: {
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            $('#ajax_response_login').html(result); // Update UI.
            $('#login_modal').modal();               // Unhide view.
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
        }
    });
}
        
/**
 *  Function will call AJAX function to load the register.
 */
function ajax_popup_register()
{
    var url = 'register_modal';
            
    $.ajax( url, {
        data: {
           'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'post',
        success: function(result) {
            // success code execution here
            $('#ajax_response_register').html(result); // Update UI.
            $('#register_modal').modal();               // Unhide view.
        },
        error: function(xhr,status,error) {
            // error code here
        },
        complete: function(xhr,status) {
            // completion code here
        }
    });
}

/**
 *  Sends a message.
 */
/**
 *  Function will call AJAX function to load the register.
 */
function ajax_send_message()
{
    $('#id_send_msg_btn').prop("disabled", true);
    $.ajax( 'save_contact_us_message', {
           data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'name': $("#id_name").val(),
                'email': $("#id_email").val(),
                'phone': $("#id_phone").val(),
                'message': $("#id_message").val(),
                'captcha_0': $("#id_captcha_0").val(),
                'captcha_1': $("#id_captcha_1").val(),
           },
           type: 'post',
           success: function(result) {
                // success code execution here
                if (result.status == 'success')
                {
                    $('#id_contact_name_danger').html('');
                    $('#id_contact_email_danger').html('');
                    $('#id_contact_phone_danger').html('');
                    $('#id_contact_message_danger').html('');
                    $('#id_contact_captcha_danger').html('');
                    alert("Message sent!");
                    window.location = ''
                }
                else
                {
                    refresh_captcha();
                    var data = $.parseJSON(result.message)
                    var name_msg = '';
                    var email_msg = '';
                    var phone_msg = '';
                    var message_msg = '';
                    var captcha_msg = '';
                    for (var key in data) {
                        if (data.hasOwnProperty(key)) {
                            if (key == 'name')
                            {
                                name_msg = data[key];
                            }
                            if (key == 'email')
                            {
                                email_msg = data[key];
                            }
                            if (key == 'phone')
                            {
                                phone_msg = data[key];
                            }
                            if (key == 'message')
                            {
                                message_msg = data[key];
                            }
                            if (key == 'captcha')
                            {
                                captcha_msg = data[key];
                            }
                        }
                    }
           
                    $('#id_contact_name_danger').html(name_msg);
                    $('#id_contact_email_danger').html(email_msg);
                    $('#id_contact_phone_danger').html(phone_msg);
                    $('#id_contact_message_danger').html(message_msg);
                    $('#id_contact_captcha_danger').html(captcha_msg);
                }
           },
           error: function(xhr,status,error) {
                // error code here
           },
           complete: function(xhr,status) {
                // completion code here
                $('#id_send_msg_btn').prop("disabled", false);
           }
    });
}


/**
 * The following function will cause the captcha to refresh.
 */
function refresh_captcha()
{
    var url = location.protocol + "//" + window.location.hostname + ":" + location.port + "/captcha/refresh/";
    
    // Make the AJAX-call
    $.getJSON(url, {}, function(json) {
              //var $form = $('modal-body').parents('register_form');
              var $form = $('#contactForm');
              $form.find('input[name="captcha_0"]').val(json.key);
              $form.find('img.captcha').attr('src', json.image_url);
              });
              return false;
}

// Add refresh button after field (this can be done in the template as well)
$('img.captcha').after(
    $('<a href="#void" class="captcha-refresh">Refresh</a>')
);

// Click-handler for the refresh-link
$('.captcha-refresh').click(function(){
    refresh_captcha();
});
</script>
<script>


jQuery(document).ready(function($){
	var contentSections = $('.cd-section'),
		navigationItems = $('#cd-vertical-nav a');
		headerNavigationItems = $('#headerNavigationItems a');

	updateNavigation();
	$(window).on('scroll', function(){
		updateNavigation();
	});

	//smooth scroll to the section
	navigationItems.on('click', function(event){
        event.preventDefault();
        smoothScroll($(this.hash));
    });

	//smooth scroll to the section
	headerNavigationItems.on('click', function(event){
        event.preventDefault();
        smoothScroll($(this.hash));
    });

    //smooth scroll to second section
    $('.cd-scroll-down').on('click', function(event){
        event.preventDefault();
        smoothScroll($(this.hash));
    });

    //open-close navigation on touch devices
    $('.touch .cd-nav-trigger').on('click', function(){
    	$('.touch #cd-vertical-nav').toggleClass('open');

    });
    //close navigation on touch devices when selectin an elemnt from the list
    $('.touch #cd-vertical-nav a').on('click', function(){
    	$('.touch #cd-vertical-nav').removeClass('open');
    });

	function updateNavigation() {
		contentSections.each(function(){
			$this = $(this);
			var activeSection = $('#cd-vertical-nav a[href="#'+$this.attr('id')+'"]').data('number') - 1;
			if ( ( $this.offset().top - $(window).height()/2 < $(window).scrollTop() ) && ( $this.offset().top + $this.height() - $(window).height()/2 > $(window).scrollTop() ) ) {
				navigationItems.eq(activeSection).addClass('is-selected');
			}else {
				navigationItems.eq(activeSection).removeClass('is-selected');
			}
		});
	}

	function smoothScroll(target) {
        $('body,html').animate(
        	{'scrollTop':target.offset().top - 90},
        	900
        );
	}
});
</script>